---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: contents-pv-volume
  labels:
    type: host-path
spec:
  storageClassName: host-mnt
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/mitayatsu/contents"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contents-pv-claim
spec:
  storageClassName: host-mnt
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
     storage: 10Gi
